yarnPath: .yarn/releases/yarn-3.5.0.cjs

packageExtensions:
    docsify-cli@4:
        dependencies:
            ansi-colors: 4
            y18n: 5
    docsify-server-renderer@4:
        dependencies:
            marked: 4
            prismjs: 1
            strip-indent: 3
